### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [FraSharp/aub#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by FraSharp** [comment]
hi, sorry for the late response, i've added it with this commit, 7c141a30d0426f2981e4373631af6c784f965c32
